version: '3'

services:

  laravel:
    build: 
      context: ./laravel-app
      dockerfile: Dockerfile.prod
    image: wesleymassine/laravel:prod
    container_name: laravel-app
    networks:
    - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: wesleymassine/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge